name: sbi-workshop
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python=3.7.10
- pytorch=1.8.1
- scikit-learn
- jupyter
- jupyterlab
- scipy
- nbstripout
- jupyter_contrib_nbextensions
- pip
- pip:
  - "sbi==0.16.0"
  - "rise==5.7.1"
  - sbibm
  - sdeint
  - jupyter-black
